---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - ./kyverno-vcluster-policy.yaml
  - ./bswe/groups.yaml
  - ./bswe/docusaurus.yaml
  # - ./bswe/vcluster.yaml
  # - ./bswe/vcluster-hostpath-mapper.yaml
  # - ./bswe/vcluster-demo-app.yaml
  # - ./bswe/cluster-access.yaml
