---
apiVersion: v1
kind: Secret
metadata:
  name: bitnami-repository
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  url: registry-1.docker.io/bitnamicharts
  enableOCI: "true"
