---
harbor:
  updateStrategy:
    type: Recreate

  expose:
    type: ingress
    ingress:
      hosts:
        core: registry.hochschule-burgenland.muehlbachler.xyz
      annotations:
        cert-manager.io/cluster-issuer: cluster-issuer-muehlbachler-xyz
        external-dns.alpha.kubernetes.io/provider: public
        external-dns.alpha.kubernetes.io/target: 178.63.69.250,2a01:4f8:121:14e2:100:3:3:1
        traefik.ingress.kubernetes.io/router.tls: "true"

  externalURL: https://registry.hochschule-burgenland.muehlbachler.xyz

  persistence:
    enabled: true
    persistentVolumeClaim:
      registry:
        storageClass: zfs
        size: 25Gi
      jobservice:
        jobLog:
          storageClass: zfs
          size: 5Gi
      database:
        storageClass: zfs
        size: 5Gi
      redis:
        storageClass: zfs
        size: 5Gi
      trivy:
        storageClass: zfs
        size: 25Gi

  imageChartStorage:
    type: gcs
    gcs:
      bucket: harbor-a24964b0-32e7-4792-8dc4-5c0b27237405
      existingSecret: google-credentials

  existingSecretAdminPassword: admin-password

  ipFamily:
    ipv4:
      enabled: true
    ipv6:
      enabled: false

  logLevel: warning
  metrics:
    enabled: true

  cache:
    enabled: true
    expireHours: 24

  core:
    existingSecret: harbor-secrets
    existingXsrfSecret: harbor-secrets

  jobservice:
    existingSecret: harbor-secrets

  registry:
    existingSecret: harbor-secrets
    credentials:
      username: harbor_registry_user
      htpasswdString: "$apr1$5kvwehx2$4jdTxm8Lt3LlLBfVVeOdy0"

  trivy:
    severity: "LOW,MEDIUM,HIGH,CRITICAL"
