---
vcluster:
  sync:
    toHost:
      configMaps:
        all: true
      secrets:
        all: true
      ingresses:
        enabled: true
      storageClasses:
        enabled: true
      persistentVolumes:
        enabled: true    
    fromHost:
      ingressClasses:
        enabled: true

  controlPlane:
    distro:
      k8s:
        enabled: true
        image:
          tag: v1.33.4

    coredns:
      deployment:
        resources:
          limits:
            memory: 256Mi
            cpu: 500m
    
    service:
      annotations:
        traefik.ingress.kubernetes.io/service.serversscheme: https
    
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: cluster-issuer-muehlbachler-xyz
        external-dns.alpha.kubernetes.io/provider: public
        external-dns.alpha.kubernetes.io/target: 178.63.69.250,2a01:4f8:121:14e2:100:3:3:1
        traefik.ingress.kubernetes.io/router.tls: "true"

    statefulSet:
      resources:
        limits:
          memory: 768Mi
          cpu: 500m
          ephemeral-storage: 2Gi
      persistence:
        volumeClaim:
          enabled: auto
          size: 5Gi
          storageClass: zfs

  deploy:
    kubeProxy:
      enabled: true

  integrations:
    metricsServer:
      enabled: true
      nodes: true
      pods: true

  policies:
    resourceQuota:
      enabled: false
    limitRange:
      enabled: false
    networkPolicy:
      enabled: false

  telemetry:
    enabled: false
