apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cluster-config
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.requests.size }}
