---
name: X
accessGroup1: ""
accessGroup2: ""
accessPrefix: "fhburgenland-bswe:swm2-ws2025-group-"

applyPolicies: true

repoURL: https://github.com/fhburgenland-bswe/swm2-ws2025-kubernetes-applications.git
