---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: ghcr-credentials
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "fh-burgenland-argocd/ghcr-credentials"
stringData:
  .dockerconfigjson: "{}"
