---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./quota.yaml
  - ./appproject.yaml
  # - ./application.yaml # FIXME: include once repository is available
