---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: fh-bswe-group-{{ .Values.name }}
  namespace: fh-burgenland-argocd
  labels:
    {{- include "bswe-group.labels" . | nindent 4 }}
spec:
  permitOnlyProjectScopedClusters: false
  description: FH Burgenland BSWE Group {{ .Values.name }}
  sourceRepos:
    - '*'
  sourceNamespaces:
    - fh-burgenland-argocd
    - {{ .Release.Namespace }}
  destinations:
    - namespace: {{ .Release.Namespace }}
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: '*'
      kind: 'Application'
    - group: '*'
      kind: Deployment
    - group: '*'
      kind: ReplicaSet
    - group: '*'
      kind: Pod
    - group: '*'
      kind: StatefulSet
    - group: '*'
      kind: Service
    - group: '*'
      kind: ConfigMap
    - group: '*'
      kind: Secret
    - group: '*'
      kind: Ingress
  roles:
    - name: fh-bswe-group-{{ .Values.name }}
      description: "privileges to group-{{ .Values.name }}"
      policies:
        - "p, proj:fh-bswe-group-{{ .Values.name }}:fh-bswe-group-{{ .Values.name }}, applications, *, *, allow"
      groups:
      {{- if .Values.accessGroup1 }}
        - {{ .Values.accessPrefix }}{{ .Values.accessGroup1 }}
      {{- else }}
        - {{ .Values.accessPrefix }}{{ .Values.name }}
      {{- end }}
      {{- if .Values.accessGroup2 }}
        - {{ .Values.accessPrefix }}{{ .Values.accessGroup2 }}
      {{- end }}
