---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: group-quota-resources
  labels:
    {{- include "bswe-group.labels" . | nindent 4 }}
spec:
  hard:
    requests.cpu: 500m
    requests.memory: 1Gi
    requests.storage: 0Gi
    requests.ephemeral-storage: 0Gi
    limits.cpu: "1"
    limits.memory: 2Gi
    limits.ephemeral-storage: 0Gi

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: group-quota-objects
  labels:
    {{- include "bswe-group.labels" . | nindent 4 }}
spec:
  hard:
    pods: "3"
    services: "3"
    services.nodeports: "0"
    services.loadbalancers: "0"
    configmaps: "10"
    secrets: "10"
    persistentvolumeclaims: "0"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: group-limit-range
  labels:
    {{- include "bswe-group.labels" . | nindent 4 }}
spec:
  limits:
    - default:
        memory: 64Mi
        cpu: 10m
      defaultRequest:
        memory: 32Mi
        cpu: 5m
      min:
        memory: 8Mi
        cpu: 1m
      max:
        memory: 1Gi
        cpu: 500m
      type: Container
