---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: registry-credentials
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "argocd/registry-credentials"
  labels:
    {{- include "bswe-group.labels" . | nindent 4 }}
stringData:
  .dockerconfigjson: "{}"
