---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: vcluster-quota-resources
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 3Gi
    requests.storage: 3Gi
    requests.ephemeral-storage: 3Gi
    limits.cpu: "3"
    limits.memory: 3Gi
    limits.ephemeral-storage: 5Gi

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: vcluster-quota-objects
spec:
  hard:
    pods: "10"
    services: "15"
    services.nodeports: "3"
    services.loadbalancers: "0"
    configmaps: "20"
    secrets: "15"
    persistentvolumeclaims: "5"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: vcluster-limit-range
spec:
  limits:
    - default:
        memory: 64Mi
        cpu: 10m
      defaultRequest:
        memory: 32Mi
        cpu: 5m
      min:
        memory: 8Mi
        cpu: 1m
      max:
        memory: 1Gi
        cpu: "1"
      type: Container
