---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bswe-groups
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - group: demo
            additionalAccessGroup: ""
  template:
    metadata:
      name: "bswe-group-{{ .group }}-infrastructure"
    spec:
      project: default
      ignoreDifferences:
        - kind: Secret
          name: ghcr-credentials
          jsonPointers:
            - /data/.dockerconfigjson
      source:
        repoURL: https://github.com/muhlba91/fh-burgenland-bswe-cluster-applications
        path: charts/bswe-group
        targetRevision: HEAD
        helm:
          valuesObject:
            group: "{{ .group }}"
            additionalAccessGroup: "{{ .additionalAccessGroup }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: fh-bswe-group-{{ .group }}
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
        syncOptions:
          - RespectIgnoreDifferences=true
          - CreateNamespace=true
          - FailOnSharedResource=true
