---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bswe-vcluster-hostpath-mapper
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: demo
          - name: a
          - name: b
          - name: c
          - name: d
          - name: e
          - name: f
  template:
    metadata:
      name: "cluster-hostpath-mapper-group-{{ .name }}"
      namespace: fh-burgenland-argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/muhlba91/fh-burgenland-bswe-cluster-applications
        path: charts/vcluster-hpm
        targetRevision: HEAD
        helm:
          releaseName: "cluster-hostpath-mapper-{{ .name }}"
          valuesObject:
            vcluster-hpm:
              VclusterReleaseName: "cluster-{{ .name }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "cluster-{{ .name }}"
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - FailOnSharedResource=true
